name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: 17
      - name: run tests
        run: sbt 'clean; scalafmtCheckAll; test'
