name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6.0.2
      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - name: Cache scala dependencies
        uses: coursier/cache-action@v8
      - name: Run tests
        run: sbt 'scalafmtCheckAll; test'
